version: "2"
linters:
  default: none
  enable:
    - dupl
    - errcheck
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - unused
  settings:
    dupl:
      threshold: 400
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
